import { mapAuditLogSourceToViewModel } from './audit-log.adapters';
import { type AuditLogSource } from './audit-log.models';

export const AUDIT_LOG_SOURCES_MOCK: AuditLogSource[] = [
  {
    id: 'evt-1001',
    actorId: 'user-1942',
    actorName: 'Е.С. Деркач',
    actorEmail: 'admin@notary.local',
    actorRole: 'Администратор',
    action: 'user.role_changed',
    actionTitle: 'Изменение роли пользователя',
    actionSubtitle: 'Applicant -> Notary',
    actionCategory: 'Изменение ролей',
    entityType: 'User',
    entityId: 'U-1942',
    entityTitle: 'Пользователь #U-1942',
    entitySubtitle: 'Раздел "Пользователи"',
    entityLabel: 'Пользователи',
    source: 'Web admin panel',
    location: 'Раздел "Пользователи и заказы"',
    ipAddress: '10.14.7.18',
    createdAt: '2026-02-28T14:18:00Z',
    severity: 'critical',
    severityLabel: 'Критично',
    isSecurityEvent: true,
    securityRiskLevel: 'high',
    reason: 'Ручная корректировка доступа',
    changes: {
      before: ['role: applicant', 'access_scope: base'],
      after: ['role: notary', 'access_scope: documents, orders'],
    },
  },
  {
    id: 'evt-1002',
    actorId: 'user-superluchito',
    actorName: 'SuperLuchito',
    actorEmail: 'admin@notary.local',
    actorRole: 'Администратор',
    action: 'audit.exported',
    actionTitle: 'Экспорт журнала',
    actionSubtitle: 'CSV по фильтру "Безопасность"',
    actionCategory: 'Экспорт',
    entityType: 'System',
    entityId: 'audit-export-18-452',
    entityTitle: 'Audit log export',
    entitySubtitle: '18 452 записи',
    entityLabel: 'Система',
    source: 'Web admin panel',
    location: 'Мониторинг и логи',
    ipAddress: '10.14.7.18',
    createdAt: '2026-02-28T13:42:00Z',
    severity: 'warning',
    severityLabel: 'Предупреждение',
    isSecurityEvent: true,
    securityRiskLevel: 'medium',
    reason: 'Служебная выгрузка для проверки инцидента',
    changes: {
      before: ['filters.security_only: false', 'filters.date_from: 2026-02-01'],
      after: ['filters.security_only: true', 'export.format: csv'],
    },
  },
  {
    id: 'evt-1003',
    actorId: 'notary-118',
    actorName: 'Анастасия Е.',
    actorEmail: 'notary@notary.local',
    actorRole: 'Нотариус',
    action: 'assessment.status_changed',
    actionTitle: 'Принят заказ в работу',
    actionSubtitle: 'Статус: New -> In Progress',
    actionCategory: 'Операции с заказами',
    entityType: 'Assessment',
    entityId: 'A-88349',
    entityTitle: 'Заказ #A-88349',
    entitySubtitle: 'Оценка недвижимости',
    entityLabel: 'Заказы',
    source: 'Notary cabinet',
    location: 'Личный кабинет нотариуса',
    ipAddress: '10.15.2.91',
    createdAt: '2026-02-28T12:57:00Z',
    severity: 'info',
    severityLabel: 'Инфо',
    isSecurityEvent: false,
    securityRiskLevel: 'low',
    reason: 'Изменение статуса при начале обработки',
    changes: {
      before: ['status: new', 'assignee: null'],
      after: ['status: in_progress', 'assignee: notary_118'],
    },
  },
  {
    id: 'evt-1004',
    actorId: 'system',
    actorName: 'system',
    actorEmail: 'security-bot',
    actorRole: 'Система',
    action: 'user.blocked',
    actionTitle: 'Блокировка подозрительного входа',
    actionSubtitle: '4 ошибки авторизации подряд',
    actionCategory: 'Безопасность',
    entityType: 'User',
    entityId: 'U-2011',
    entityTitle: 'Пользователь #U-2011',
    entitySubtitle: 'IP: 91.214.44.18',
    entityLabel: 'Пользователи',
    source: 'Auth gateway',
    location: 'Шлюз авторизации',
    ipAddress: '91.214.44.18',
    createdAt: '2026-02-28T11:06:00Z',
    severity: 'critical',
    severityLabel: 'Критично',
    isSecurityEvent: true,
    securityRiskLevel: 'high',
    reason: 'Автоматическое правило antifraud',
    changes: {
      before: ['login_attempts: 3', 'status: active'],
      after: ['login_attempts: 4', 'status: temporarily_blocked'],
    },
  },
  {
    id: 'evt-1005',
    actorId: 'payments-admin-1',
    actorName: 'Евгений Т.',
    actorEmail: 'payments@notary.local',
    actorRole: 'Администратор',
    action: 'payment.created',
    actionTitle: 'Создание платежа',
    actionSubtitle: 'Ручная корректировка счета',
    actionCategory: 'Платежи',
    entityType: 'Payment',
    entityId: 'P-5104',
    entityTitle: 'Платеж #P-5104',
    entitySubtitle: '2 500 ₽',
    entityLabel: 'Платежи',
    source: 'Admin / Payments',
    location: 'Платежный модуль',
    ipAddress: '10.14.7.31',
    createdAt: '2026-02-27T19:24:00Z',
    severity: 'success',
    severityLabel: 'Успешно',
    isSecurityEvent: false,
    securityRiskLevel: 'low',
    reason: 'Исправление реквизитов и перевыпуск счета',
    changes: {
      before: ['payment.status: pending', 'payment.amount: 0'],
      after: ['payment.status: created', 'payment.amount: 2500'],
    },
  },
  {
    id: 'evt-1006',
    actorId: 'security-admin-1',
    actorName: 'Дмитрий Ч.',
    actorEmail: 'security@notary.local',
    actorRole: 'Администратор',
    action: 'security.policy.updated',
    actionTitle: 'Изменение политики сессий',
    actionSubtitle: 'TTL сессии сокращён с 12 до 8 часов',
    actionCategory: 'Безопасность',
    entityType: 'System',
    entityId: 'security-policy',
    entityTitle: 'Security policy',
    entitySubtitle: 'Config / session',
    entityLabel: 'Система',
    source: 'Admin / Settings',
    location: 'Настройки безопасности',
    ipAddress: '10.14.7.55',
    createdAt: '2026-02-27T17:40:00Z',
    severity: 'warning',
    severityLabel: 'Предупреждение',
    isSecurityEvent: true,
    securityRiskLevel: 'medium',
    reason: 'Актуализация политики доступа',
    changes: {
      before: ['session.ttl_hours: 12', 'revoke_on_password_change: false'],
      after: ['session.ttl_hours: 8', 'revoke_on_password_change: true'],
    },
  },
];

export const AUDIT_LOGS_MOCK = AUDIT_LOG_SOURCES_MOCK.map(mapAuditLogSourceToViewModel);
